Repository PicadaARSW/WhereWeFront, pull requests merged in 2025-03, with the labels that each got.

#2 Create README.md
  README.md
Labels: documentation

#3 ADD:USERSAVE IN DATABASE
  App.js
  UserContext.jsx
  api/ApiClient.js
  auth/AuthManager.js
  graph/GraphManager.js
  menus/DrawerMenu.jsx
  screens/CalendarScreen.jsx
  screens/HomeScreen.jsx
  screens/SignInScreen.jsx
Labels: bug

#6 ADD: feature location screen
  App.js
  api/ApiClient.js
  graph/GraphManager.js
  location/LocationSocket.js
  package-lock.json
  package.json
  screens/GroupDetailScreen.jsx
  screens/GroupMapScreen.jsx
  screens/GroupsScreen.jsx
  screens/HomeScreen.jsx
  screens/SignInScreen.jsx
Labels: bug

#7 fix desing and add new favorite place management
  api/ApiClient.js
  assets/WhereWeImg.jpg
  components/GroupItem.jsx
  location/LocationSocket.js
  menus/DrawerMenu.jsx
  package-lock.json
  package.json
  screens/GroupDetailScreen.jsx
  screens/GroupMapScreen.jsx
  screens/GroupsScreen.jsx
  screens/HomeScreen.jsx
  screens/SignInScreen.jsx
  styles/HomeScreenStyles.js
  styles/SigninScreenStyles.js
Labels: feature
